version: "3"

services:
  mysql-db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: forum_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
